"""Embedding-based merchant categorizer for SoloLedger.

Level 2: sits between exact-match (Categorizer) and human review.
Uses sentence-transformers (all-MiniLM-L6-v2, ~22MB) to find similar
merchants in the pre-trained reference database.

Usage:
    from app.categorizer_embed import EmbedCategorizer
    cat = EmbedCategorizer()
    result = cat.suggest("AMAZON MKTPLACE PMTS")
    # → {merchant: "...", account: "Expenses:Software:SaaS",
    #    confidence: 0.94, similar_to: "AMAZON.COM"}

    # Suggest with confidence labels (compatible with Categorizer interface)
    result = cat.suggest_with_confidence("UBER RIDE")
    # → {account: "Expenses:Travel", confidence: "high", ...}

Requires: pip install sentence-transformers
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path
from typing import Any, Optional


def _get_embedder():
    """Lazy-load sentence-transformers model.

    Raises ImportError instead of calling sys.exit — a missing optional
    dependency must never kill the API process (SystemExit isn't caught
    by the categorizer's `except Exception`).
    """
    global _MODEL
    if "_MODEL" not in globals() or _MODEL is None:
        from sentence_transformers import SentenceTransformer
        _MODEL = SentenceTransformer("all-MiniLM-L6-v2")
    return _MODEL.encode


def _cosine_sim(a, b):
    dot = sum(x * y for x, y in zip(a, b))
    na = math.sqrt(sum(x * x for x in a))
    nb = math.sqrt(sum(x * x for x in b))
    return dot / (na * nb) if na and nb else 0.0


class EmbedCategorizer:
    """Merchant-name categorizer using embedding semantic similarity.

    Loads the reference database from the `merchant_map.json` file that
    was generated by the training pipeline. Falls back to a built-in
    reference database for merchants not yet seen.
    """

    def __init__(self, merchant_map_path: str | Path | None = None):
        project_root = Path(__file__).resolve().parent.parent
        self._map_path = Path(merchant_map_path or project_root / "merchant_map.json")

        # Reference data: list of {name, account}
        self._references: list[dict] = []
        self._embeddings: list[list[float]] = []
        self._loaded = False

    def _load(self):
        if self._loaded:
            return

        embedder = _get_embedder()

        # Build reference list from merchant_map.json if it exists
        if self._map_path.exists():
            data = json.loads(self._map_path.read_text())
            for merchant_upper, accounts in data.items():
                best_acct = max(accounts, key=lambda a: accounts[a])
                self._references.append({
                    "name": merchant_upper,
                    "account": best_acct,
                })

        if not self._references:
            print("Warning: no reference data found. Run training pipeline first.",
                  file=sys.stderr)
            return

        # Embed all reference names
        texts = [r["name"] for r in self._references]
        self._embeddings = embedder(texts, show_progress_bar=False).tolist()
        self._loaded = True

    def suggest(self, merchant: str, top_k: int = 3) -> dict[str, Any]:
        """Suggest a Beancount account for a merchant name.

        Returns dict with keys:
            merchant_name: the input
            account: best matching account (or None)
            confidence: similarity score 0-1
            similar_to: closest merchant in reference data
            alternatives: list of {account, merchant, confidence}
        """
        self._load()
        embedder = _get_embedder()

        # Also check exact match first (from existing merchant_map)
        key = merchant.upper().strip()
        map_path = self._map_path
        if map_path.exists():
            data = json.loads(map_path.read_text())
            if key in data:
                accounts = data[key]
                best = max(accounts, key=lambda a: accounts[a])
                return {
                    "merchant_name": merchant,
                    "account": best,
                    "confidence": 1.0,
                    "similar_to": key,
                    "alternatives": [],
                }

        # Embed query
        query_emb = embedder([merchant], show_progress_bar=False)[0].tolist()

        if not self._embeddings:
            return {
                "merchant_name": merchant,
                "account": None,
                "confidence": 0.0,
                "similar_to": None,
                "alternatives": [],
            }

        # Score all references
        scored = []
        for i, ref_emb in enumerate(self._embeddings):
            sim = _cosine_sim(query_emb, ref_emb)
            scored.append((sim, i))

        scored.sort(key=lambda x: -x[0])
        top_sim, top_idx = scored[0]

        if top_sim < 0.3:
            return {
                "merchant_name": merchant,
                "account": None,
                "confidence": 0.0,
                "similar_to": None,
                "alternatives": [],
            }

        ref = self._references[top_idx]
        alternatives = []
        for sim, idx in scored[1:top_k]:
            alt = self._references[idx]
            alternatives.append({
                "account": alt["account"],
                "merchant": alt["name"][:40],
                "confidence": round(sim, 4),
            })

        return {
            "merchant_name": merchant,
            "account": ref["account"],
            "confidence": round(top_sim, 4),
            "similar_to": ref["name"][:60],
            "alternatives": alternatives,
        }

    def suggest_with_confidence(self, merchant: str) -> dict:
        """Compatible interface with Categorizer.suggest_with_confidence()."""
        result = self.suggest(merchant)

        if result["account"] is None:
            return {
                "account": None,
                "count": 0,
                "total": 0,
                "confidence": "none",
            }

        ratio = result["confidence"]
        if ratio >= 0.9:
            label = "high"
        elif ratio >= 0.6:
            label = "medium"
        elif ratio >= 0.4:
            label = "low"
        else:
            label = "none"

        return {
            "account": result["account"],
            "count": 1,
            "total": 1,
            "confidence": label,
        }
